Repository Picktartup/Picktartup-frontend, pull requests merged in 2024-12, with the labels that each got.

#25 feat: 투자 시 지갑 비밀번호 입력 및 전자서명 url 전달
  src/components/modal/InvestmentModal.jsx
Labels: enhancement

#27 feat: 회원가입, 로그인 페이지 구현
  src/components/signup/Steps.jsx
  src/components/signup/WalletSuccessDialog.jsx
  src/layouts/auth/index.jsx
  src/routes.js
  src/views/auth/SignIn.jsx
  src/views/auth/SignUpStep1.jsx
  src/views/auth/SignUpStep2.jsx
Labels: enhancement

#29 fix: CI 오류 해결
  package-lock.json
  package.json
Labels: bug

#33 feat: Nginx api별 라우팅
  .gitignore
  nginx.conf
  package-lock.json
  package.json
  src/setupProxy.js
Labels: enhancement

#34 cicd: api 호출 형식 통일
  nginx.conf
  src/views/auth/SignIn.jsx
  src/views/auth/SignUpStep1.jsx
  src/views/auth/SignUpStep2.jsx
Labels: bug

#36 cicd: EKS와 온프레미스 K8S에서의 API 처리 방식 변경
  nginx.conf
Labels: bug

#37 feat: Nginx CORS 정책 추가 및 JWT Token 디코딩
  nginx.conf
  package-lock.json
  package.json
  src/utils/jwtUtils.js
  src/views/main/token/components/ExchangeTable.jsx
  src/views/main/token/components/PurchaseTable.jsx
  src/views/main/token/index.jsx
Labels: config

#38 fix: utils 경로 수정
  src/views/main/token/components/ExchangeTable.jsx
  src/views/main/token/components/PurchaseTable.jsx
  src/views/main/token/index.jsx
Labels: bug

#39 fix: utils import 형태 수정
  src/utils/jwtUtils.js
Labels: bug

#40 cicd: API 라우팅 수정
  nginx.conf
Labels: config

#45 fix: 투자 시 AccessToken 검증
  package.json
  src/components/modal/InvestmentModal.jsx
  src/views/auth/SignUpStep2.jsx
  src/views/main/history/ContractDetail.jsx
  src/views/main/history/index.jsx
Labels: enhancement

#52 ✨ feat: 결제 시 toast로 로딩 처리 및 잔액 반영
  src/components/card/NftCard.jsx
  src/components/modal/InvestmentModal.jsx
  src/views/main/default/details.jsx
  src/views/main/token/components/PurchaseTable.jsx
Labels: enhancement
